### ISSUE TITLE
Pigs Galore

### ISSUE THREAD

**Issue by GridFreelancer** [RacoonDog/Fixed-Glow-Squids#1]
For whatever reason, this mod alters the pig spawning to the extreme. I have a short video attached showing me freshly downloading the mod and fabric API to ensure that there was no tomfoolery on my part. I set the seed to 120 so I would spawn in a plains biome to easily see the number of pigs that spawn. The video quality is kinda bad cause I compressed it so I can upload it here.

https://user-images.githubusercontent.com/91971335/136064309-92f4fa37-ae2a-4f95-abd7-227679bba41f.mp4

**Comment by crosby-moe** [comment]
jesus christ

**Comment by crosby-moe** [comment]
oh god i have a theory on why that is
since i used a gross hack to delete the actual glow squid entity from the game (returning EntityType.build without adding to the registry when registering the entity), when it tries to actually spawn them, it looks in the registry, finds nothing so defaults to pig and since those... idk have much different spawn conditions and whatnot it just goes ham

**Comment by crosby-moe** [comment]
im out of ideas

**Comment by GridFreelancer** [comment]
The only thing I could think of to do is instead of removing glow squid spawning, just replace them with regular squids.

**Comment by crosby-moe** [comment]
> The only thing I could think of to do is instead of removing glow squid spawning, just replace them with regular squids.

that would drastically increase the spawn rate of squids like it did with pigs

**Comment by crosby-moe** [comment]
by the way, i figured out a way to fix it, im just upgrading the code to allow better compatibility
